# Generated by Django 5.0.7 on 2024-07-13 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('favorite_food', models.CharField(max_length=30)),
                ('added_to_zoo', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('zookeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
